### ISSUE TITLE
AdGoBye does not account for pedestals

### ISSUE THREAD

**Issue by uslashdeleted** [AdGoBye/AdGoBye#90]
```
Unhandled exception. System.InvalidOperationException: The instance of entity type 'Content' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, Nullable`1 fallbackState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityStates(IEnumerable`1 entities, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.AddRange(IEnumerable`1 entities)
   at AdGoBye.Indexer.CommitToDatabase(DatabaseOperationsContainer container)
   at AdGoBye.Indexer.AddToIndex(IEnumerable`1 paths)
   at AdGoBye.Indexer.ManageIndex()
   at Program.<Main>$(String[] args)
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
```

[appsettings.json](https://github.com/user-attachments/files/16117316/appsettings.json)

**Comment by regalialong** [comment]
That is very weird, despite our efforts, AGB appears to be indexing something twice. We might be able to catch this but I'm not quite sure how this happened in the first place.

**Comment by regalialong** [comment]
Try out this [artifact](https://github.com/AdGoBye/AdGoBye/actions/runs/9822905590) so we can see what ID it doesn't like, from there we'd have to see what is duplicated and for what reason.

Does the same happen if you regenerate your database? For that, just rename `database.db` to something else like `database.db.bak` and let it make a new index.

**Comment by uslashdeleted** [comment]
`Unhandled exception. System.InvalidOperationException: The instance of entity type 'Content' cannot be tracked because another instance with the key value '{Id: avtr_c86b83bb-9d0d-4366-a997-776df4474066}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.`

Regenerating the database does not help the issue, the new `database.db` has no differences.
[database.db.zip](https://github.com/user-attachments/files/16118147/database.db.zip)

I think it might be a duplicate in the game's cache? I can't find any exact duplicates of the avatar's __data file though.

**Comment by regalialong** [comment]
This should be a duplicate, yeah, the only cases where there should happen is is newer versions (which we inherently handle so that we can repatch) or impostors.

If you don't want to go through the chore of debugging and if you can afford it, clearing your cache should fix this.

Otherwise, [I put together a small script for you](https://github.com/user-attachments/files/16118610/publish.zip), taking some logic from the Indexer to try to find the duplicate.
Give it the path to your cache folder as first argument and assuming that my code doesn't explode horribly, it should print you the duplicates.

**Comment by uslashdeleted** [comment]
The script unfortunately did explode :(

```
[11:38:17 INF] Walking C:\Users\lyn\AppData\LocalLow\Game\Game\Cache-WindowsPlayer\7C65788041D4AE78
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AssetsTools.NET.AssetTypeTemplateField.FromTypeTree(TypeTreeType, Int32&)
   at AssetsTools.NET.AssetTypeTemplateField.FromTypeTree(TypeTreeType, Int32&)
   at AssetsTools.NET.Extra.AssetsManager.GetTemplateBaseField(AssetsFileInstance, AssetsFileReader, Int64, Int32, UInt16, AssetReadFlags)
   at AssetsTools.NET.Extra.AssetsManager.GetTemplateBaseField(AssetsFileInstance, AssetFileInfo, AssetReadFlags )
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Program.<<Main>$>g__ParseFile|0_0(String, DirectoryInfo, <>c__DisplayClass0_0&)
   at Program.<Main>$(String[])
```

[Full output](https://github.com/user-attachments/files/16118729/duplicatefinder_output.txt)

I don't mind going through the debugging process with you

**Comment by regalialong** [comment]
Oh boy this is starting to get weird, that threw really deep into AssetsTools. I'm not sure what's causing that but I've wrapped it in a try catch for now.

[publish.zip](https://github.com/user-attachments/files/16118862/publish.zip)

**Comment by uslashdeleted** [comment]
[output.txt](https://github.com/user-attachments/files/16118924/output.txt)
It exploded even more :(

**Comment by regalialong** [comment]
Oops, flipped a condition I shouldn't have.
[publish.zip](https://github.com/user-attachments/files/16118939/publish.zip)

**Comment by uslashdeleted** [comment]
[output.txt](https://github.com/user-attachments/files/16118940/output.txt)

still broken :(

**Comment by regalialong** [comment]
Something makes me think I should probably retry this with more sleep :^)
Here, hopefully this one doesn't have the fuckup, including symbols helps a good amount
[publish.zip](https://github.com/user-attachments/files/16118954/publish.zip)

**Comment by uslashdeleted** [comment]
```
[13:23:28 INF] Walking C:\Users\lyn\AppData\LocalLow\Game\Game\Cache-WindowsPlayer\7C65788041D4AE78
[13:23:28 ERR] Attempting to parse Id from C:\Users\lyn\AppData\LocalLow\Game\Game\Cache-WindowsPlayer\7C65788041D4AE78/00000000000000000000000027000000 caused an exception: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AssetsTools.NET.AssetTypeTemplateField.FromTypeTree(TypeTreeType, Int32&)
   at AssetsTools.NET.AssetTypeTemplateField.FromTypeTree(TypeTreeType, Int32&)
   at AssetsTools.NET.Extra.AssetsManager.GetTemplateBaseField(AssetsFileInstance, AssetsFileReader, Int64, Int32, UInt16, AssetReadFlags)
   at AssetsTools.NET.Extra.AssetsManager.GetTemplateBaseField(AssetsFileInstance, AssetFileInfo, AssetReadFlags )
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Program.<<Main>$>g__ParseFile|0_0(String, DirectoryInfo, <>c__DisplayClass0_0&)
```
[output.txt](https://github.com/user-attachments/files/16118978/output.txt)

Do you want me to send over the cache file for this so you can get a better idea on what's going on?

**Comment by regalialong** [comment]
Sure, would be nice if you could chitchat to me either on Matrix per `@hellbeast:catgirl.cloud` or on Discord per `1024720274928697384` for it, either works.

**Comment by regalialong** [comment]
Okay, for permanence, I took a look and there's two independent things that happened with DuplicateFinder:
- `GetBaseField` can fail to deserialize a MonoBehaviour, bubbling up `IndexOutOfRangeException`
- For some ungodly reason, here we did have duplicates (that is Content with the same ID that doesn't share a `StableContentHash`).

The first one is easy and will just require a try catch, I'll open an issue for this in a moment.

The second one I'll assume is a weird fluke since I didn't see it on other players before, I'm not sure how this could happen and it breaks the assumptions on how the Cache works for the Indexer. 

If `StableContentHash` is not unique (in a way parsable to us), then we're back to the drawing board on how to track Content to begin with.

Told OP to clear their Cache, if this is a fluke then that should do it, so I'll close this for now and it can be reopened at another point if it crops up again.

**Comment by regalialong** [comment]
Alright, update after a thread on Matrix.

Uh, the bug is that we check for the item `blueprintId` within a MonoBehaviour, which happens to be shared with pedestals as well.
That's a bit awkward. 

Either way, the fix for this should be fairly simple.
